program: src/mlops_group_11/train.py
name: hyperparameters_sweep
project: mlops_group_11
method: bayes

metric:
  goal: minimize
  name: val/loss

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}

parameters:
  hyperparameters.lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.1
  hyperparameters.batch_size:
    values: [16, 32, 64]
  hyperparameters.epochs:
    values: [5, 10, 15]
  hyperparameters.prob_threshold:
    distribution: uniform
    min: 0.1
    max: 0.9
  model.name:
    values: ["csatv2_21m.sw_r512_in1k", "resnet50", "efficientnet_b0"]

run_cap: 10
